image:
  repository: vlad1slavik
  tag: "v1.2.0-660ae95"
  arch: amd64
# Додатково визначте секцію для токену TELE_TOKEN
secret:
  name: "kbot"
  env: "8556644419:AAEzbHy_1-RqVqVkdxW9hzbwmuWmvz90X_0"
  key: "token"
securityContext:
  privileged: true
